### ISSUE TITLE
App Icon is broken

### ISSUE THREAD

**Issue by RealDyllon** [enjoy-learning-play-safe/hexapod-app#12]

**Comment by Lil-YH** [comment]
![logo](https://user-images.githubusercontent.com/73232658/127143214-b1d9fd75-4953-4372-a0c6-87edda3da2a2.png)

**Comment by RealDyllon** [comment]
@Lil-YH Is the icon still broken on your windows build?

**Comment by Lil-YH** [comment]
> @Lil-YH Is the icon still broken on your windows build?

Yes
