### ISSUE TITLE
Adding dynamic limits to 6dof inputs and checking for invalid actuator positions during interpolate 

### ISSUE THREAD

**Issue by RecruitKen** [enjoy-learning-play-safe/hexapod-app#14]
Use the relationship of `y = hardcodedmaxlimit * e^(-0.25*(x-1))` to dynamically change the maximum axes input depending on the number of non zero axes. Use a threshold of around 20 or 30% before it is recognised as a new non zero input 

hardcodedmaxlimit is the values 100 for XY, 150 for Z, 30 degrees for the 3 rotations. 

x would be the number of non zero axes, ranging from 1 to 6. I guess 0 should be considered but it should be defaulted to the hardcodedmaxlimit. 

The power of -0.25 can be changed to tune the changing of the dynamic limits.

Movements with maxed z translation tend to hit the ends of actuator. We can consider using a separate power value for z so that it scales down faster compared to the other 5. 

Part 2, 
Some posed would be impossible, for example z translation of -150 and a yaw of 30. 
As all actuator would bottom out at the endstops to achieve z=-150, it would not be possible to do a yaw or any other movement as they would require the lowering of some actuators. 

This issue might be solved through the dynamic limit setting, if so then it would not be an issue. I will be running some test to check this.

**Comment by Tnsolace** [comment]
![Uploading image_2021-07-24_12-20-38.png…]()

**Comment by RecruitKen** [comment]
![Limits](https://user-images.githubusercontent.com/84618709/127140208-2511328f-dc02-4568-a83d-8afddc79c64b.JPG)
