### ISSUE TITLE
Replace TF gcode with JS arrays

### ISSUE THREAD

**Issue by RealDyllon** [enjoy-learning-play-safe/hexapod-app#20]
TF decimals are not exact compared to np and JS arrays.

Due to an issue with TFJS, that the maintainers don't really care about, we lose precision in decimals (possible due to how the tfjs library handles float32 values in the system).

@RecuitKen, we need to implement a native matmul function that handles JS array.

**Comment by RecruitKen** [comment]
I think math.js has a native matrix multiplication. math.multiply(array1 , array2)


Also at what dp does the error start appearing? Past 6 dp the maximum error will be +-0.0005mm for our current config. It would be somewhat negligible for our use case.
